### ISSUE TITLE
not working with sensu go beta 8

### ISSUE THREAD

**Issue by craigpfeiffer** [bukiadeniji/sensu2-pagerduty-plugin#1]
i just applied this patch to a sensu go environment taht is beta 8 just wondering if you have used it at this point.  i know some things have changed since then, but it doesn't seem what you changed should have been impacted.

i'm seeing the following error

`{"assets":null,"component":"pipelined","handler":"pagerduty-3_occur","level":"info","msg":"event pipe handler executed","namespace":"default","output":"sh: /usr/share/pdagent-integrations/bin/pd-sensu: not found\n","status":127,"time":"2018-11-30T22:21:46Z"}`

**Comment by bukiadeniji** [comment]
That version does not work with beta 8.

Please see the official release here - https://github.com/sensu/sensu-pagerduty-handler

I put together a quick start guide for the official version here - https://github.com/bukiadeniji/Sensu-Go-Pagerduty-Plugin-Quick-Start

If you are still on the beta release, you can try this [patch](https://github.com/bukiadeniji/sensu-go-pagerduty-plugin-patch)
